### ISSUE TITLE
Windows CSGO Server compatibility?

### ISSUE THREAD

**Issue by Porcellacion** [sazonische/disable_agent_models#1]
Hello,

Is there any plans on making this work for Windows? I'm currently hosting 16 servers for pretty competitive teams and they always ask eachother to turn off agent models. We would like to change that so that they don't have to.

But our servers are being hosted on windows machines, so we need .dll file instead of .so

If time is possible, this would be great. Also, does this plugin force all the CT's and T's to have the same default playermodel or does this actually only disable the agent-models and it's still randomized default models?

Great work however, cheers!

**Comment by sazonische** [comment]
Not planned yet
This disables all the functionality of the agents

**Comment by sazonische** [comment]
> Hello,
> 
> Is there any plans on making this work for Windows? I'm currently hosting 16 servers for pretty competitive teams and they always ask eachother to turn off agent models. We would like to change that so that they don't have to.
> 
> But our servers are being hosted on windows machines, so we need .dll file instead of .so
> 
> If time is possible, this would be great. Also, does this plugin force all the CT's and T's to have the same default playermodel or does this actually only disable the agent-models and it's still randomized default models?
> 
> Great work however, cheers!

https://forums.alliedmods.net/showpost.php?p=2762730&postcount=18
