### ISSUE TITLE
The windows solution isn't working

### ISSUE THREAD

**Issue by Porcellacion** [sazonische/disable_agent_models#2]
Expected behavior: Everything should work as usual except that agent models isn't enabled.

Actual behavior: The server crashes when someone gets killed in warmup.
The knives and gloves doesn't show for people.

**Comment by sazonische** [comment]
@yourmnbbn Can you help?

**Comment by sazonische** [comment]
> Expected behavior: Everything should work as usual except that agent models isn't enabled.
> 
> Actual behavior: The server crashes when someone gets killed in warmup. The knives and gloves doesn't show for people.


write the data about the server, say server console status and version

**Comment by yourmnbbn** [comment]
> @yourmnbbn Can you help?

Yeah, I'll take a look later in the day.

**Comment by sazonische** [comment]
> > @yourmnbbn Can you help?
> 
> Yeah, I'll take a look later in the day.

Thanks so much

**Comment by Porcellacion** [comment]
I have sourcemod version: 1.11.0.6746
The plugin version it the latest one from this github, not modified what so ever.
I am running in with splewis get5 plugin.

**Comment by yourmnbbn** [comment]
Confirmed that it did crash when player died in warmup using this plugin. The current implementation of windows modech is just a copy of the linux one, accidentally back then my simple test case didn't cover all this. Looks like we need some changes to the original implementation to make it properly work on windows. I did have fixed this crash, but there are some other problems about the windows modelch that need to be fixed. So it would take some time, maybe a few days or so.

**Comment by yourmnbbn** [comment]
@Porcellacion As for this
> The knives and gloves doesn't show for people.

I don't have this problem in the test case. My test environment only has this plugin and modelch extension, as well as the official plugins and extensions. Can you provide sm plugins list or some specific problem models?

**Comment by Porcellacion** [comment]
Tried it after the last commit, it seems to work fine. I'll apply it to the matches for tonight and get back to you with information regarding if it works for full servers or not.

**Comment by Porcellacion** [comment]
Works perfectly now, thanks for the last commit.
